import { LoanProduct, } from "@/lib/types/GlobalTypes";
import { PiggyBank, Calendar, User, Landmark, Users, Briefcase, Shield, ArrowRight, ArrowLeftRight, CheckCircle, Percent, Clock, Wallet, Lock, } from "lucide-react";


export const loanProducts: LoanProduct[] = [
    {
        id: "Bank Loan",
        title: "Bank Loan",
        subtitle: "Micro-savings for daily wage earners",
        description: "यस सहकारी संस्थाले विभिन्न किसिमका बचत सर्वशुलभ व्याज दरमा उपलब्ध गराउँछ, समुह बचत, कर्जा सुरक्षण कोष, बाल बचत, खुत्रुके बचत, कर्मचारी संचयकोष, अन्तर समुह बचत, विशेष वचत निकै सरल तरिकाबाट उपलब्ध गराउछ ।",
        icon: Calendar,
        accentColor: "#14b8a6",
        features: [
            { icon: Percent, label: "Interest Rate", value: "8.5% p.a." },
            { icon: Wallet, label: "Min. Balance", value: "Rs. 500" },
            { icon: Clock, label: "Tenure", value: "Flexible" },
        ],
        facilities: ["Daily collection service", "Instant SMS notification", "ATM facility available", "मेरो नाम मोहन वली हो"],
    },
    {
        id: "Home Loan",
        title: "Home Loan",
        subtitle: "Systematic investment plan",
        description: "Build your wealth with a fixed monthly deposit. Perfect for salaried individuals looking for disciplined growth.",
        icon: PiggyBank,
        accentColor: "#3b82f6",
        features: [
            { icon: Percent, label: "Interest Rate", value: "9.0% p.a." },
            { icon: Wallet, label: "Min. Deposit", value: "Rs. 1,000" },
            { icon: Clock, label: "Tenure", value: "1–5 Years" },
        ],
        facilities: ["Auto-debit from bank", "Loan against deposit", "High interest returns"],
    },
    {
        id: "Personal Loan",
        title: "Personal Loan",
        subtitle: "Secure your child's future",
        description: "A dedicated savings plan for your child's education and future needs. Start early, save big.",
        icon: Calendar,
        accentColor: "#ec4899",
        features: [
            { icon: Percent, label: "Interest Rate", value: "9.5% p.a." },
            { icon: Wallet, label: "Min. Deposit", value: "Rs. 500" },
            { icon: Lock, label: "Lock-in", value: "Until 18 yrs" },
        ],
        facilities: ["Education bonus", "Insurance coverage", "Guardian operated"],
    },
    {
        id: "livestock-Loan",
        title: "livestock-Loan",
        subtitle: "Agro-based financial support",
        description: "Designed for farmers to manage income from livestock sales and purchase fodder during dry seasons.",
        icon: Calendar,
        accentColor: "#f59e0b",
        features: [
            { icon: Percent, label: "Interest Rate", value: "8.0% p.a." },
            { icon: Wallet, label: "Min. Balance", value: "Rs. 200" },
            { icon: Clock, label: "Type", value: "Recurring" },
        ],
        facilities: ["Seasonal withdrawal", "Agro-insurance link", "Vet discount partners"],
    },
    {
        id: "Overdraft Loan",
        title: "Overdraft Loan",
        subtitle: "Flexible savings account",
        description: "A regular savings account with full liquidity. Deposit and withdraw anytime you need.",
        icon: User,
        accentColor: "#6366f1",
        features: [
            { icon: Percent, label: "Interest Rate", value: "6.0% p.a." },
            { icon: Wallet, label: "Min. Balance", value: "Rs. 1,000" },
            { icon: Clock, label: "Access", value: "Instant" },
        ],
        facilities: ["Unlimited withdrawals", "Mobile Banking", "Cheque book facility"],
    },
    {
        id: "EMI",
        title: "EMI loan",
        subtitle: "High returns, low risk",
        description: "Lock your funds for a fixed tenure and enjoy the highest interest rates with guaranteed returns.",
        icon: Landmark,
        accentColor: "#8b5cf6",
        features: [
            { icon: Percent, label: "Interest Rate", value: "10.5% p.a." },
            { icon: Wallet, label: "Min. Deposit", value: "Rs. 10,000" },
            { icon: Clock, label: "Tenure", value: "1–10 Years" },
        ],
        facilities: ["Highest rate guarantee", "Monthly interest payout option", "Premature closure facility"],
    },
    {
        id: "group-Loan",
        title: "Group Saving",
        subtitle: "Community banking",
        description: "Save together as a community or cooperative. Pool resources for larger investments and loans.",
        icon: Users,
        accentColor: "#06b6d4",
        features: [
            { icon: Percent, label: "Interest Rate", value: "8.0% p.a." },
            { icon: Users, label: "Min. Members", value: "5 Persons" },
            { icon: Clock, label: "Meeting", value: "Monthly" },
        ],
        facilities: ["Group loan access", "Democratic decision making", "Leadership training"],
    },
    {
        id: "epf",
        title: "Employee Provident Fund",
        subtitle: "Retirement planning",
        description: "Corporate managed savings for employee retirement. Both employer and employee contributions.",
        icon: Briefcase,
        accentColor: "#64748b",
        features: [
            { icon: Percent, label: "Interest Rate", value: "Gov. Rate" },
            { icon: Briefcase, label: "Eligibility", value: "All Staff" },
            { icon: Lock, label: "Withdrawal", value: "Resign / Retire" },
        ],
        facilities: ["Tax benefits", "Employer matching", "Gratuity integration"],
    },
    {
        id: "insurance-saving",
        title: "Insurance Saving",
        subtitle: "Protection + Savings",
        description: "A hybrid product combining life insurance coverage with systematic savings accumulation.",
        icon: Shield,
        accentColor: "#ef4444",
        features: [
            { icon: Percent, label: "Interest Rate", value: "7.5% p.a." },
            { icon: Shield, label: "Coverage", value: "Life + Health" },
            { icon: Clock, label: "Term", value: "Long Term" },
        ],
        facilities: ["Risk coverage", "Maturity bonus", "Tax deduction"],
    },
    {
        id: "intergroup-saving",
        title: "Intergroup Saving",
        subtitle: "Cross-community lending",
        description: "Facilitates saving and lending between different cooperative groups within the organization.",
        icon: ArrowLeftRight,
        accentColor: "#f97316",
        features: [
            { icon: Percent, label: "Interest Rate", value: "Variable" },
            { icon: ArrowLeftRight, label: "Scope", value: "Internal" },
            { icon: Clock, label: "Settlement", value: "Quarterly" },
        ],
        facilities: ["Internal clearing house", "Group accountability", "Low default risk"],
    },
];